name: Frontend CI 

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:   # optional (manual trigger)

  frontend:
    name: Frontend CI
    runs-on: self-hosted
    needs: backend
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build